### ISSUE TITLE
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

### ISSUE THREAD

**Issue by omegasoft7** [pinterest/android-pdk#1]
when i add this into my project i see this error for most of my images! what should i do to solve it?

**Comment by sahilmiglani** [comment]
@omegasoft7  it looks like an open issue on Google buildTools
https://code.google.com/p/android/issues/detail?id=77704

You can try one of the solution from the above link:
Select "compile independent modules in parallel" under compiler preferences.

Let me know if it works.

**Comment by Zehhu** [comment]
Closing this for cleanup.
