### ISSUE TITLE
 Activity Not Found Exception when trying to connect with Pinterest 

### ISSUE THREAD

**Issue by Singwai** [pinterest/android-pdk#22]
With the latest Pinterest update (5.21.2),  connecting with Pinterest app will always throw Activity Not Found exception.

```
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.pinterest/com.pinterest.sdk.PinterestOauthActivity}; have you declared this activity in your AndroidManifest.xml?
```

The activity (com.pinterest.sdk.PinterestOauthActivity) that handles the auth intent was either marked private, renamed or deleted in the latest version of Pinterest app.

Here is the code that creates the intent:

``` java
private Intent createAuthIntent(Context context, String appId, List<String> permissions) {
        return new Intent()
            .setClassName(PINTEREST_PACKAGE, PINTEREST_OAUTH_ACTIVITY)
            .putExtra(PDKCLIENT_EXTRA_APPID, appId)
            .putExtra(PDKCLIENT_EXTRA_APPNAME, "appName")
            .putExtra(PDKCLIENT_EXTRA_PERMISSIONS, TextUtils.join(",", permissions));
    }
```

https://github.com/pinterest/android-pdk/blob/master/pdk/src/main/java/com/pinterest/android/pdk/PDKClient.java#L464-L470

Here is the line that uses the intent and where the exception is thrown:

``` java
    private void openPinterestAppForLogin(Context c, Intent intent) {
        try {
            //Utils.log("PDK: starting Pinterest app for auth");
            ((Activity)c).startActivityForResult(intent, PDKCLIENT_REQUEST_CODE);
        } catch (ActivityNotFoundException e) {
            // Ideally this should not happen because intent is not null
            // initiate web login??
            Utils.loge("PDK: failed to open Pinterest App for login");
            return;
        }
        return;
    }
```

https://github.com/pinterest/android-pdk/blob/master/pdk/src/main/java/com/pinterest/android/pdk/PDKClient.java#L451-L462

**Comment by Singwai** [comment]
I believe the activity is renamed to "com.pinterest.classic.sdk.PinterestOauthActivity" but I have never tested it yet

**Comment by aamitgupta** [comment]
Yes It is working ("com.pinterest.classic.sdk.PinterestOauthActivity"), i have checked.
