### ISSUE TITLE
Using PDK client, If Pinterest app not installed then while callback it is launching new activity instead of redirecting to current activity.

### ISSUE THREAD

**Issue by bhoslenayan25** [pinterest/android-pdk#31]
Using PDK client, If Pinterest app not installed then callback is launching new activity instead of redirecting to current activity.
Manifest file:
`<activity
        android:name=".PostActivity"
        android:label="@string/app_name">
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="pdk4888100843754107022" />
        </intent-filter>
    </activity>`
Activity:
`List scopes = new ArrayList<String>();
    scopes.add(PDKClient.PDKCLIENT_PERMISSION_READ_PUBLIC);
    scopes.add(PDKClient.PDKCLIENT_PERMISSION_WRITE_PUBLIC);

    pdkClient.login(this, scopes, new PDKCallback() {
        @Override
        public void onSuccess(PDKResponse response) {
            Log.d(getClass().getName(),"Login: " +response.getData().toString());
            try {
                onLoginSuccess();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        @Override
        public void onFailure(PDKException exception) {
            Log.e(getClass().getName(), exception.getDetailMessage());
        }
    });`

**Comment by Zehhu** [comment]
Linking this to #25 since that entire flow will be looking at a rewrite
