### ISSUE TITLE
Unable to pin the image to Pinterest using sdk in android studio.

### ISSUE THREAD

**Issue by gworldtech** [pinterest/android-pdk#32]
I am using Android Studio 2.2.3 with pinterest android sdk" android-pdk" .
I want to  pin the image from my application to Pinterest.
I am using Createpin method for pin the image but i am getting following exception:
{"message": "You need to upload an image or provide the 'image_url' parameter", "type": "api"}

**Comment by Zehhu** [comment]
Doing a cleanup of this project and looks like this task was never addressed.

I'm going to close this for now.
