### ISSUE TITLE
PDK login leads to crash the Pinterest app when not started the app.

### ISSUE THREAD

**Issue by fbvictorhugo** [pinterest/android-pdk#44]
When call " pdkClient.login(this, scope, ...)" and the app Pinterest is not started, my app close and android says "Pinterest has stopped". None callback on login with PDK.

This bug similar to issue #37, but this case I logged the pinterest app, but is not started recently.

**Comment by jalpa1234** [comment]
I am also facing the same issue. 
It is showing below error

Unable to start activity ComponentInfo{com.pinterest/com.pinterest.sdk.PinterestOauthActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.CookieStore java.net.CookieManager.getCookieStore()' on a null object reference at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)

Please help...

**Comment by Zehhu** [comment]
Related to https://github.com/pinterest/android-pdk/issues/37
