### ISSUE TITLE
Decouple Model Classes from android packages.

### ISSUE THREAD

**Issue by paoloantinori** [pinterest/android-pdk#6]
Hi, I'm writing an Apache Camel component to integrate with Pinterest API.

The java SDK assumes being an Android environment and referenciate some platform packages.

Would you consider re-package and isolate at least models to an independent package?

**Comment by Zehhu** [comment]
Doing a cleanup of this project and looks like this task was never addressed. 

I'm going to close this for now. In the future, we may explore this but we have a lot of higher priority issues we should focus on.
